version: '3'

services:
  postgres-compose:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./python:/externo
      - ./postgres:/scripts

  python-compose:
    image: python-mh
    ports:
      - "8888:8888"
    volumes:
      - ./python:/app/externo

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:    
      PGADMIN_DEFAULT_EMAIL: "a@b"
      PGADMIN_DEFAULT_PASSWORD: "a"
    ports:
      - "80:80"
    depends_on:
      - postgres-compose
